version: "1"

services:
  jenkins:
    hostname: jenkins
    image: jenkins/jenkins:lts-jdk17
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
    restart: always
    environment:
      - JAVA_OPTS=-Duser.timezone=Asia/Tokyo -Dfile.encoding=UTF-8
    networks:
      - jg_network

  gitbucket:
    hostname: gitbucket
    image: gitbucket/gitbucket:latest
    ports:
      - "80:8080"
      - "29418:29418"
    volumes:
      - ./gitbucket_data:/gitbucket
    restart: always
    networks:
      - jg_network
        
networks:
  jg_network:
    driver: bridge
