version: '3.4'

x-common-settings: &common-settings
  restart: always

services:
  jenkins:
    <<: *common-settings
    hostname: jenkins
    image: jenkins/jenkins:lts-jdk21
    volumes:
      - ./jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Duser.timezone=Asia/Tokyo -Dfile.encoding=UTF-8
      - JENKINS_OPTS=--prefix=/jenkins
    networks:
      - jgnet

  gitbucket:
    <<: *common-settings
    hostname: gitbucket
    image: gitbucket/gitbucket:latest
    environment:
      GITBUCKET_PREFIX: /gitbucket
    volumes:
      - ./gitbucket_data:/gitbucket
    networks:
      - jgnet

  proxy:
    <<: *common-settings
    build: proxy
    depends_on:
      - jenkins
      - gitbucket
    links:
      - gitbucket:gitbucket
      - jenkins:jenkins
    ports:
      - "80:80"
    networks:
      - jgnet

networks:
  jgnet:
    driver: bridge
