version: "3.4"

x-common-settings: &common-settings
  restart: always

services:
  jenkins:
    <<: *common-settings
    hostname: jenkins
    image: jenkins/jenkins:lts-jdk21
    volumes:
      - ./jenkins_home:/var/jenkins_home
    ports:
      - "8081:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS=-Duser.timezone=Asia/Tokyo -Dfile.encoding=UTF-8
      # - JENKINS_OPTS=--prefix=/jenkins
    networks:
      - jgnet

  gitbucket:
    <<: *common-settings
    hostname: gitbucket
    image: gitbucket/gitbucket:latest
    ports:
      - "80:8080"
      - "29418:29418"
    # environment:
    #   GITBUCKET_PREFIX: /gitbucket
    volumes:
      - ./gitbucket_data:/gitbucket
    networks:
      - jgnet

networks:
  jgnet:
    driver: bridge
